# 5. Neuron-Batch Input

In [13]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [14]:
# define input batch of five
X = np.array([[2.3,4.5,1.3],[-1.1,3.2,-2],[-.2,1.9,3],[-.2,-.1,.4],[-.1,-.3,-.2]])
print(X)

[[ 2.3  4.5  1.3]
 [-1.1  3.2 -2. ]
 [-0.2  1.9  3. ]
 [-0.2 -0.1  0.4]
 [-0.1 -0.3 -0.2]]


In [15]:
# define weights as w
w = np.array([3.2,-1.9,2.5])

# define bias
b = np.array([-1])

In [16]:
# define sigmoid and relu functions (activation functions)
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def relu(x):
    return np.maximum(0,x)

In [17]:
# define neuron_output
def neuron_output(X,w,b,phi): 
    z = np.dot(w,X.T)+b
    return phi(z)

In [20]:
# Compute neuron output for batch of inputs

print(neuron_output(X,w,b, sigmoid))

print(neuron_output(X,w,b, relu))

[0.74 0.   0.9  0.39 0.22]
[1.06 0.   2.25 0.   0.  ]


In [21]:
# create Neuron class
class Neuron:
    def __init__(self, neuron_input,weights,bias,activation_function):
        self.w = weights
        self.b = bias
        self.X = neuron_input
        self.phi = activation_function
    def calc_output(self):
        z = np.dot(self.w,self.X.T) + self.b
        a = self.phi(z)
        return a

In [22]:
# instantiate neuron class and calculate output for relu activation function
Neuron_relu = Neuron(X,w,b,relu)
Neuron_relu.calc_output()

array([1.06, 0.  , 2.25, 0.  , 0.  ])

In [23]:
Neuron_sigmoid = Neuron(X,w,b,sigmoid)
Neuron_sigmoid.calc_output()

array([0.74, 0.  , 0.9 , 0.39, 0.22])